<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Controllers\" />
    <Folder Include="Middlewares\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeamProjectManagement.Application\TeamProjectManagement.Application.csproj" />
    <ProjectReference Include="..\TeamProjectManagement.Infrastructure\TeamProjectManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
